development:
  adapter: postgresql
  encoding: unicode
  database: remind-lemonheads_development
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

test:
  adapter: postgresql
  encoding: unicode
  database: remind-lemonheads_test
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

production:
  adapter: postgresql
  encoding: unicode
  database: remind-lemonheads_production
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>